[package]
name = "papyrus-wallpaper"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
rfd = "0.12"
tempfile = "3.20.0"
winreg = "0.11"
winapi = { version = "0.3", features = ["winuser"] }
image = { version = "0.24", features = ["png", "jpeg", "bmp"] }


